name: flutter_anime_app
description: "Anime recommendation app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  logger: ^2.5.0
  auto_route: ^9.3.0+1
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  auto_route_generator: ^9.3.1
  injectable_generator: ^2.7.0

flutter:


  uses-material-design: true

  assets:
    - assets/