name: Flutter CI/CD

on:
  push:
    branches:
      - main # Запускать pipeline только для ветки main
  pull_request:
    branches:
      - main # Запускать pipeline для PR в main

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
      # 1. Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка Flutter SDK
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Укажите нужную версию Flutter

      # 3. Получение зависимостей
      - name: Install dependencies
        run: flutter pub get

      # 4. Анализ кода
      - name: Analyze code
        run: flutter analyze

      # 5. Запуск тестов
      - name: Run tests
        run: flutter test

      # 6. Сборка APK (для Android)
#      - name: Build Android APK
#        run: flutter build apk --release

      # 7. Сборка IPA (для iOS, требует macOS runner)
      # - name: Build iOS IPA
      #   run: flutter build ipa --release

      # 8. Архивация артефактов
      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk