name: Flutter CI/CD

on:
  push:
    branches:
      - main # Запускать pipeline только для ветки main
  pull_request:
    branches:
      - main # Запускать pipeline для PR в main

jobs:
  build:
    runs-on: ubuntu-latest # Используем последнюю версию Ubuntu

    steps:
      # 1. Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настройка Flutter SDK
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Укажите нужную версию Flutter

      # 3. Получение зависимостей
      - name: Install dependencies
        run: flutter pub get

      # 4. Анализ кода
      - name: Analyze code
        run: flutter analyze

      # 5. Запуск тестов
      - name: Run tests
        run: flutter test

#      # 6. Установка Fastlane
#      - name: Install Fastlane
#        run: |
#          brew install fastlane
#
#      # 7. Выполнение Fastlane iOS Beta
#      - name: Run Fastlane iOS Beta
#        run: |
#          cd ios
#          fastlane ios beta